/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserComponent: typeof import('./src/components/user/Component.vue')['default']
    UserHelloWorld: typeof import('./src/components/user/HelloWorld.vue')['default']
  }
}

// For TSX support
declare global {
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UserComponent: typeof import('./src/components/user/Component.vue')['default']
  const UserHelloWorld: typeof import('./src/components/user/HelloWorld.vue')['default']
}